ALTER TABLE users ADD COLUMN date_of_birth VARCHAR(20) AFTER country;
ALTER TABLE users ADD COLUMN push_notifications BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN email_alerts BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN login_notifications BOOLEAN DEFAULT TRUE;
