# TiDB Cloud Connection
spring.datasource.url=jdbc:mysql://${DATABASE_HOST:gateway01.eu-central-1.prod.aws.tidbcloud.com}:${DATABASE_PORT:4000}/${DATABASE_NAME:acme_financial}?useSSL=true&sslMode=REQUIRED&enabledTLSProtocols=TLSv1.2,TLSv1.3
spring.datasource.username=${DATABASE_USER:386moUkwsw8zREP.root}
spring.datasource.password=${DATABASE_PASS:tLzll0DfKoXBGSmU}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.address=0.0.0.0


spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

application.security.jwt.secret-key=YTM0YmNjOTRmYjkzZGEyNTAyNGY3OWU0NThiMGVmYTM2YjJlYTJlMTY3MzRjNGRmMTc3MmZlNjU4NDNlMDUzMQ==
application.security.jwt.expiration=86400000

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
server.port=${PORT:8081}

# OUTBOUND MESSAGING NODE (SMS - DEPRECATED)
# twilio.account_sid=...
# twilio.auth_token=...
# twilio.from_number=...

# OUTBOUND MESSAGING NODE (BREVO REST API)
spring.mail.password=${MAIL_PASS:sjrzrnhrwsgfiaib}
mail.from=${MAIL_FROM:omoebt06@gmail.com}

# CLOUD STORAGE (CLOUDINARY)
cloudinary.cloud_name=dcskr2gcf
cloudinary.api_key=878829784384122
cloudinary.api_secret=_oAbEOB-0TDNMLkp8TeImQv5KKM

# API ACCELERATION (GZIP)
server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
server.compression.min-response-size=1024

# DATABASE OPTIMIZATION
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=10000